spring:
  application:
    name: orders
  datasource:
    url: jdbc:postgresql://147.45.151.57:5432/itumandeev?currentSchema=orders
    username: itumandeev
    password: itumandeev
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      default_schema: orders
  liquibase:
      enabled: true
      change-log: classpath:db/changelog/changelog-master-orders.xml
server:
  port: 8081
logging:
  level:
    root: INFO
    org:
      apache:
        kafka: WARN